{% set name = "GPy" %}
{% set version = "1.9.2" %}
{% set sha256 = "372e43d41df5c90e0958d3073070994b351a7409c2e5fbd349cffe13bc24c10a" %}


package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
    - scipy >=0.16
    - six
  run:
    - python
    - paramz >=0.8.5
    - {{ pin_compatible('numpy') }}
    - scipy >=0.16
    - six
    - matplotlib

test:
  imports:
    - GPy

about:
  home: http://github.com/SheffieldML/GPy
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: 'The Gaussian Process Toolbox'
  doc_url: https://pythonhosted.org/GPy/
  dev_url: https://github.com/SheffieldML/GPy

extra:
  recipe-maintainers:
    - dirmeier
