travis:
  secure:
    BINSTAR_TOKEN: U9EZGb0kFV7uJvUumVKZF8pCmD5GsQgLQeu5XHYmiXyggnDrIggb4Vpvu54m7cTOui/gARFTkS2fJYv8tHU0dbRTJrEZf7L5UNGWiYxD9E2Ief6a6+TOnIIdcMyp2BkgL4MgwUiTpM8GT0znFmrbiSwEhrPq2yVMFqV0/ndewfvCwAY5UaSwUNNBngj+7raf2TUjLaYnNGg1Wb/apgv912GUzsSRHB4AckqpDO7Y8dm4ewoKcwyo2AQK4rHcMsMg6Dbv08JL5DuTJ9VLuu3ImBBelmgXodacqVgbrQsFaI6i4EDW55wmoAUFxPdAxXrkdQ/nwQJ0PvGN32sQXEbTK3vVFNfWqCZ/nTWiUPVnJhI1OjpUzOWB4nv6Va/y11Btr+X+WB61BJQsRhPVt6h5/tKrfCkANbIyT5moyEjoUwFV/Ul++uWb1DTAwUD5T2nNlZVV8MUV4QHn73+qu9EMMjpLrrAMviYEGKA3lPKieRBWubcum9JUZTpAJV/igiWW2f/mZbkXfSh5IFUH2j5KS+ESmvw25Amfb7StjzbiOHrtgg0ZRyMWQNWj9GmUekncTSejnPB7PH/nZniNXMKQ8qKmUMnwb98y+YpJZ1QigAamuzUhbJnXs0PIhNBldFGqQpHVCcdc4aeL4sFLz7EccpZnfjzcXBEto85rds0T8m0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
