travis:
  secure:
    BINSTAR_TOKEN: B1r057u2akEShV86cIbPytVhIMeOmwsjpm6FJckeTTti0+IexAV7MRJOnOg9YozfWDdXYmrTiCUjbKc/XIirutyYLyGEI/rSjcSBhPW7QHDFzAVJAKoU3y6cwMFTtgFWLCBBq21L6hD9R/sDKFKYKKgET4jS/qF39ZSonyS8EY1u+fMv3hG7WtLcy4MHK1W+UHkbpEb40FPG3huk3Cabe0H3SdvL0z675mpxXPmIjj6tMHqehGYE74x43Zb8ltvugkbtl0yONqnfF8bj4sYncB128wLOwZXq5I/M8yEH/6Hhj8oepQpvIw2Coqi0q/aaEVsijr2eHj356MgKydL6E6ahXbeL/Cvvh+75liCbwYH3M1C9TqHeYe3c6389WmYXouXiix4o256iXonhW+u3S0nQS9zoyMLE9diLwIBjAGu5OXslkWzp16sv8050z009+CXz+Odbj+FUhY76+0akh1fSltlnyKeX4z+970RQXFzySZvzkRlPD+w8TSjQfhmjnEeNBEboEf8P/C7VLF2sEIVSxM2S3QY0Z+c1/xPVub2VYP6oz6YxK9A12Uufjtb7hkIZNKiYDrpQVJAu6bNUJnClFr4CSjOH9Kp/mqER3b0YaAow4Y2FyJOsLHod4xJa5FAJl9/pJfJEDZ1vJBbjttGcSQJOJ4OCUSteEhbPwj0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
